const Map<String, String> ar = {
  "Welcome Back": "اهلا بعودتك",
  "UserName": "اسم المستخدم",
  "Password": "كلمة السر",
  "Login": "تسجيل الدخول",
  "Log Out": "تسجيل الخروج",
  "Home": "الصفحة الرئيسية",
  "Sales": "المبيعات",
  "About US": "من نحن",
  "Sales Return": "مرتجع المبيعات",
  "Purchases": "المشتريات",
  "Purchases Return": "مرتجع المشتريات",
  "Reports": "التقارير",
  "Setting": "الاضافات",
  "Store": "المخزن",
  "Number": "رقم",
  "Name": "الاسم",
  "From": "من",
  "To": "الي",
  "Mobile": "موبيل",
  "Date": "التاريخ",
  "Model Search": "بحث موديل",
  "Search Model": "بحث موديل",
  "Barcode": "باركود",
  "Category": "الفئة",
  "This Item is Sold Before": "هذه القطعة مباعة مسبقا",
  "Users": "المستخدمين",
  "Models": "الموديلات",
  "Spending": "المصاريف",
  "Clients": "العملاء",
  "Input": "وارد",
  "Output": "منصرف",
  "Details": "التفاصيل",
  "Stock": "المخزن",
  "Count": "الكمية",
  "Total": "الاجمالى",
  "Categories": "الفئات",
  "Select Spending": "اختر مصروف",
  "Select Category": "اختر فئة",
  "Model Code": "رقم الموديل",
  "Arabic Name": "الاسم بالعربية",
  "Category Name": "اسم الفئة",
  "Time :": "الوقت :",
  "Data :": "التاريخ :",
  "Adress": "العنوان",
  "Client Name": "اسم العميل",
  "Mobile : 01033656531": "موبيل : 01033656531",
  "1 abdelazez St. from k3abe4 next to bahr":
      "1 شارع عبد العزيز من كعابيش طابق الثانى بجوار بحر ",
  "Please Save Your Recept": "برجاء الاحتفاظ بالفاتورة",
  "Payment : Cash": "الدفع : كاش",
  "Shift :": "وردية :",
  "Recept Number :": "فاتورة رقم :",
  "Add Spending": "اضافة مصاريف",
  "Edit Spending": "تعديل مصاريف",
  "Disable Spending": "الغاء مصاريف",
  "ُEnable Spending": "استرجاع مصاريف",
  "Add Model": "اضافة موديل",
  "Edit Model": "تعديل موديل",
  "Disable Model": "الغاء موديل",
  "ُEnable Model": "استرجاع موديل",
  "Add Category": "اضافة فئة",
  "Edit Category": "تعديل فئة",
  "Disable Category": "الغاء فئة",
  "ُEnable Category": "استرجاع فئة",
  "Add User": "اضافة مستخدم",
  "Add Client": "اضافة عميل",
  "Edit User": "تعديل المستخدم",
  "Disable User": "الغاء المستخدم",
  "ُEnable User": "استرجاع المستخدم",
  "User Name": "اسم المستخدم",
  "Last Name": "اسم العائلة",
  "First Name": "الاسم الاول",
  "Spending Report": "تقرير المصاريف",
  "Stock Report": "تقرير المخزن",
  "Store Report": "تقرير المخزن",
  "Purchases Report": "تقرير المشتريات",
  "Spending Type": "فئة المصاريف",
  "Confirm Admin Password": "تأكيد باسورد الادمن",
  "Expected Profit :": "الربح المتوقع",
  "Total Sell Price :": "اجمالى سعر البيع",
  "Total Purchase Price :": "اجمالى سعر الشراء",
  "Total Cash :": "اجمالى المبلغ",
  "Total Count :": "اجمالى الكمية",
  "Invoice Number": "رقم الفاتورة",
  "End Date": "تاريخ النهاية",
  "Start Date": "تاريخ البداية",
  "Sales Report": "تقرير المبيعات",
  "Cash :": "الفرق الموجود :",
  "Cash:": "الفرق  :",
  "Output Total :": "مجموع الخوارج :",
  "Input Total :": "مجموع الدواخل :",
  "Select Zone": "اختر اهتمامك",
  "Select Report": "اختر التقرير",
  "Total Price": "السعر الاجمالى",
  "Wrong Cash": "المبلغ خطأ",
  "Cash": "المبلغ",
  "Model": "الموديل",
  "Size": "المقاس",
  "Item Transfer": "نقل منتج",
  "Color": "اللون",
  "Price": "السعر",
  "Error": "خطأ",
  "OR": "أو",
  "Please Check Your Cash": "برجاء مراجعة الخزنة",
  "Discount": "الخصم",
  "Submit": "حفظ",
  "Add Item": "اضف منتج",
  "Sell Price": "سعر البيع",
  "Purchase Price": "سعر الشراء",
  "Total :": "الاجمالى :",
  "Discount :": "الخصم :",
  "Total after Discount :": "الاجمالى بعد الخصم :",
};
