const Map<String, String> en = {
  "Welcome Back": "Welcome Back",
  "UserName": "UserName",
  "About US": "About US",
  "Password": "Password",
  "Login": "Login",
  "Log Out": "Log Out",
  "Home": "Home",
  "Sales": "Sales",
  "Sales Return": "Sales Return",
  "Purchases": "Purchases",
  "Purchases Return": "Purchases Return",
  "Reports": "Reports",
  "Setting": "Setting",
  "Store": "Store",
  "Number": "Number",
  "Name": "Name",
  "Mobile": "Mobile",
  "Users": "Users",
  "Models": "Models",
  "Spending": "Spending",
  "Clients": "Clients",
  "Input": "Input",
  "Output": "Output",
  "Stock": "Stock",
  "Count": "Count",
  "Total": "Total",
  "From": "From",
  "To": "To",
  "Adress": "Adress",
  "Model Search": "Model Search",
  "Client Name": "Client Name",
  "Select Spending": "Select Spending",
  "Select Category": "Select Category",
  "Model Code": "Model Code",
  "Categories": "Categories",
  "Arabic Name": "Arabic Name",
  "Category Name": "Category Name",
  "Data :": "Data :",
  "Time :": "Time :",
  "Mobile : 01033656531": "Mobile : 01033656531",
  "1 abdelazez St. from k3abe4 next to bahr":
      "1 abdelazez St. from k3abe4 next to bahr",
  "Please Save Your Recept": "Please Save Your Recept",
  "Payment : Cash": "Payment : Cash",
  "Shift :": "Shift :",
  "Recept Number :": "Recept Number :",
  "Add Spending": "Add Spending",
  "Edit Spending": "Edit Spending",
  "Disable Spending": "Disable Spending",
  "ُEnable Spending": "ُEnable Spending",
  "Add Model": "Add Model",
  "Edit Model": "Edit Model",
  "Disable Model": "Disable Model",
  "ُEnable Model": "ُEnable Model",
  "Add Category": "Add Category",
  "Edit Category": "Edit Category",
  "Disable Category": "Disable Category",
  "ُEnable Category": "ُEnable Category",
  "Add User": "Add User",
  "Add Client": "Add Client",
  "Edit User": "Edit User",
  "Disable User": "Disable User",
  "ُEnable User": "ُEnable User",
  "User Name": "User Name",
  "Last Name": "Last Name",
  "First Name": "First Name",
  "Spending Report": "Spending Report",
  "Store Report": "Store Report",
  "Stock Report": "Stock Report",
  "Purchases Report": "Purchases Report",
  "Spending Type": "Spending Type",
  "Expected Profit :": "Expected Profit :",
  "Total Sell Price :": "Total Sell Price :",
  "Total Purchase Price :": "Total Purchase Price :",
  "Total Cash :": "Total Cash :",
  "Total Count :": "Total Count :",
  "Invoice Number": "Invoice Number",
  "End Date": "End Date",
  "Sales Report": "Sales Report",
  "Start Date": "Start Date",
  "Details": "Details",
  "OR": "OR",
  "Error": "Error",
  "Item Transfer": "Item Transfer",
  "Please Check Your Cash": "Please Check Your Cash",
  "Search Model": "Search Model",
  "Confirm Admin Password": "Confirm Admin Password",
  "Select Report": "Select Report",
  "This Item is Sold Before": "This Item is Sold Before",
  "Cash :": "Cash :",
  "Cash:": "Cash:",
  "Output Total :": "Output Total :",
  "Input Total :": "Input Total :",
  "Select Zone": "Select Zone",
  "Date": "Date",
  "Total Price": "Total Price",
  "Barcode": "Barcode",
  "Category": "Category",
  "Cash": "Cash",
  "Wrong Cash": "Wrong Cash",
  "Model": "Model",
  "Size": "Size",
  "Color": "Color",
  "Price": "Price",
  "Sell Price": "Sell Price",
  "Purchase Price": "Purchase Price",
  "Discount": "Discount",
  "Submit": "Submit",
  "Add Item": "Add Item",
  "Total :": "Total :",
  "Discount :": "Discount :",
  "Total after Discount :": "Total after Discount :",
};
